// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// ///
// /// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// // // ...

// // await Firebase.initializeApp(
// //     options: DefaultFirebaseOptions.currentPlatform,
// // );

// //  import 'firebase_options.dart';
// //  // ...
// //  await Firebase.initializeApp(
// //    options: DefaultFirebaseOptions.currentPlatform,
// //  );
// // / ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA_NvHRJtKkMr-D1e0QqNi_aVDQziJ_GX4',
//     appId: '1:1010546939174:web:40e6aa4d81b6316e74dde7',
//     messagingSenderId: '1010546939174',
//     projectId: 'sgpa-calculator-chetan',
//     authDomain: 'sgpa-calculator-chetan.firebaseapp.com',
//     storageBucket: 'sgpa-calculator-chetan.appspot.com',
//     measurementId: 'G-2S64BC7X87',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDuRwwNS_Wr7ezZC3vLfqjml2gTrreEiQE',
//     appId: '1:1010546939174:android:a422c8743ae55cdd74dde7',
//     messagingSenderId: '1010546939174',
//     projectId: 'sgpa-calculator-chetan',
//     storageBucket: 'sgpa-calculator-chetan.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAKQH-bbnZag7HiI0qCl1o4zxvqBAMZwBg',
//     appId: '1:1010546939174:ios:e729af98cf2319cd74dde7',
//     messagingSenderId: '1010546939174',
//     projectId: 'sgpa-calculator-chetan',
//     storageBucket: 'sgpa-calculator-chetan.appspot.com',
//     iosBundleId: 'com.example.spga',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAKQH-bbnZag7HiI0qCl1o4zxvqBAMZwBg',
//     appId: '1:1010546939174:ios:d7aab06cbb52788d74dde7',
//     messagingSenderId: '1010546939174',
//     projectId: 'sgpa-calculator-chetan',
//     storageBucket: 'sgpa-calculator-chetan.appspot.com',
//     iosBundleId: 'com.example.spga.RunnerTests',
//   );
// }
